### ISSUE TITLE
acumularcambio

### ISSUE THREAD

**Issue by danitico** [i62luria/Practicas4Computacion#3]
https://github.com/i62luria/Practicas4Computacion/blob/1f194070a103de2cff3d5d3e91b4e745d3e5a3fc/IntroducionModelosComputacionales/Practica1/proyectoEclipsePr1IMC/imc/PerceptronMulticapa.cpp#L311

se te ha olvidado tener en cuenta el sesgo en deltaw
this->pCapas[i].pNeuronas[j].deltaW[0] += this->pCapas[i].pNeuronas[j].dX;

**Comment by aluquerivas-dev** [comment]
Thanks
